### ISSUE TITLE
Borked on NetBSD

### ISSUE THREAD

**Issue by herrhotzenplotz** [pankunull/ppaste#2]
Running ppaste on NetBSD reveals some incompatiblities:

```console
indium$ opaste
uname: unknown option -- o
usage: uname [-amnprsv]
/home/nsonack/.local/bin/opaste: sha256sum: not found
Usage: opaste [OPTIONS] <file1> <file...>
Try 'opaste --help' for more information.
indium$ 
```

- uname -o should be uname -s. That should also be compatible with other OSes.
- sha256sum is not a thing. Better use sha256 on *BSD.

**Comment by pankunull** [comment]
Fixed! 

Sorry for the uber delay...

Thanks (:
